### ISSUE TITLE
is this no longer updated?

### ISSUE THREAD

**Issue by illtellyoulater** [questianon/sdupdates#10]

**Comment by illtellyoulater** [comment]
And... after 20 days since last update, you've only added news about the upcoming Waifu release... 

That must be really important news for you... I guess.

**Comment by USBhost** [comment]
At least he updates what's most important.

**Comment by Ezaki29** [comment]
Please stop your disrespectful behavior. Do you pay for this information? If it's free, don't complain. You can always search for updated news elsewhere or contribute something to this repo.

**Comment by aliencaocao** [comment]
@illtellyoulater how about you stop talking and start making pull requests...you do realise that you can contribute right?

**Comment by illtellyoulater** [comment]
I'm not the one who claimed I'd be maintaining "a mega collection of all resources and news related to Stable Diffusion".
You did.

**Comment by aliencaocao** [comment]
He did not claim 'I will maintain this repo and update it every x days'. Again, if you want to contribute, please open a PR, if not, stop complaining and go pay someone to do this job for you.

**Comment by illtellyoulater** [comment]
I never said you claimed you would add updates exactly every _X_ number of days. 

You are the one who described this repository as a "collection of **news**, which intrinsically implies being up to date.

If you can't live up to your own promises then it's your responsibility and you should probably think about changing this repo's description unless you are ok with people thinking (and telling you) this is not a reliable source of news.

**Comment by questianon** [comment]
Thank you everyone who's defended me so far. I've kept silent to prevent this from escalating, but it seems I need to make an official response.

**Updates**:
As far as I know, I'm the only person who's maintaining a reliable news source, a centralized repository of resources, and a tutorial all at the same time. I don't think people realize how long it takes to update all of these, especially because I try to check the resources before listing them and give some structure to the formatting. Doing this is also a hobby for me, so my real life responsibilities take precedence over updating this repository. While I love being a part of this community and finding the most relevant information to keep people up to date, I have zero financial incentive to update this repo nor have I made any promises to update it within a specific time frame (e.g. daily). So, I'll try to keep this up to date when I can, but there will be times when I don't have the time to.

**Commit**:
Regarding the most recent commit, I put a label there so people understand that while I'm reorganizing the goldmine section, I won't be updating the other two sections nor will I be online on Discord since I've overshot deadlines for this project in the past by splitting my attention between different things.

**Contributing**:
If you really want updated news when this isn't updated, you can search Reddit, 4chan, Discord, other news sites, etc, which is where I find my information. Better yet, you can contribute by submitting a PR as some people said in the comments or sending a DM to keep the repo up to date when I'm not there.

**Comment by illtellyoulater** [comment]
I didn't want in any way whatsoever to belittle your work! I am fully aware of the times that all this requires.

Sorry if I came out a bit rude... We all know the pace at which AI is going and my words came out of the frustration of not seeing this repo updated for weeks after having deeply relied on it and having suspended my search for other sources of centralized information.

Perhaps if you announced that this was not going to be updated anymore like it was (daily, or at least weekly) I would have dedicated more time to finding other sources... So naybe it's just about finding a right pace at which you can work on this and making it more clear? That's all I'm saying...

And of course if I get more free time I will be happy to help.

**Comment by Kilvoctu** [comment]
Thanks for everything you've done @questianon. Your repo is usually my 1st stop for news and resources, then otherwise I hang out in the sd subreddit.

I know for most of us who contribute stuff to the SD community are doing it as a hobby in spare time. Take your time, don't feel pressured and get burnt out.

**Comment by Yumae** [comment]
Nothing yet?

**Comment by BassJMagan** [comment]
> Thanks for everything you've done @questianon. Your repo is usually my 1st stop for news and resources, then otherwise I hang out in the sd subreddit.
> 
> I know for most of us who contribute stuff to the SD community are doing it as a hobby in spare time. Take your time, don't feel pressured and get burnt out.

Which SD subreddits have the best information for keeping up to date with the latest stuff? I'm mostly interested in anime models like anything3/waifu diffusion/NAI if that helps.

**Comment by WesleyNery** [comment]
f

**Comment by gigacoomer69** [comment]
it's over bros
sdupdates is kill

**Comment by BassJMagan** [comment]
F for sdupdates o7

**Comment by illtellyoulater** [comment]
Wtf are you on about with this kiddo jargon? Not sure it's gonna help improve the situation to a good extent...

**Comment by martianunlimited** [comment]
I have posted the rentry page and the github repository to https://www.reddit.com/r/StableDiffusion/comments/10jmk3t/we_really_need_a_new_sd_resource_goldmine/
hopefully the more knowledgable folks from the reddit community will help push some updates.

**Comment by Yumae** [comment]
"next update will be delayed"... still not a single update for two weeks after the long break. Yeah, how many times has it been now? I guess its time to stop following this project.

**Comment by BassJMagan** [comment]
> 

frfr dead af
